export interface StatRequest {
    keys: string[],
    request: (any),
}

export const statRequest: StatRequest = {
    request: (playerName: string) => `SELECT ic.id_limit,ic.id_gametype,sum(ic.cnt_hands),sum(ic.cnt_hands_won),sum(ic.amt_won),ic.limit_currency,sum(ic.amt_won_curr_conv),sum(ic.amt_expected_won_curr_conv),sum(ic.amt_bb_won),sum(ic.amt_expected_bb_won),sum(ic.cnt_vpip),sum(ic.cnt_walks),sum(ic.cnt_pfr),sum(ic.cnt_pfr_opp),sum(ic.cnt_p_3bet),sum(ic.cnt_p_3bet_opp),sum(ic.cnt_p_3bet_def_action_fold),sum(ic.cnt_p_3bet_def_opp),sum(ic.cnt_p_4bet),sum(ic.cnt_p_4bet_opp),sum(ic.cnt_p_4bet_def_action_fold),sum(ic.cnt_p_4bet_def_opp),sum(ic.cnt_p_3bet_def_action_call),sum(ic.cnt_p_4bet_after_raising),sum(ic.cnt_p_4bet_opp_when_open_raised),sum(ic.cnt_p_squeeze),sum(ic.cnt_p_squeeze_opp),sum(ic.cnt_wtsd),sum(ic.cnt_f_saw),sum(ic.cnt_wtsd_won),sum(ic.cnt_f_saw_won),sum(ic.cnt_f_cbet),sum(ic.cnt_f_cbet_opp),sum(ic.cnt_t_cbet),sum(ic.cnt_t_cbet_opp),sum(ic.cnt_r_cbet),sum(ic.cnt_r_cbet_opp),sum(ic.cnt_f_cbet_success),sum(ic.cnt_t_cbet_success),sum(ic.cnt_r_cbet_success),sum(ic.cnt_f_cbet_def_action_call),sum(ic.cnt_f_cbet_def_opp),sum(ic.cnt_t_cbet_def_action_call),sum(ic.cnt_t_cbet_def_opp),sum(ic.cnt_f_cbet_def_action_fold),sum(ic.cnt_t_cbet_def_action_fold),sum(ic.cnt_p_rfi_btn),sum(ic.cnt_p_open_opp_btn),sum(ic.cnt_p_rfi_ep),sum(ic.cnt_p_open_opp_ep),sum(ic.amt_r_call_won),sum(ic.amt_r_call),sum(ic.cnt_steal_att),sum(ic.cnt_steal_opp),sum(ic.cnt_steal_def_action_raise),sum(ic.cnt_steal_def_3bet_opp),sum(ic.cnt_steal_def_action_fold),sum(ic.cnt_steal_def_opp),sum(ic.cnt_f_bet),sum(ic.cnt_f_raise),sum(ic.cnt_t_bet),sum(ic.cnt_t_raise),sum(ic.cnt_r_bet),sum(ic.cnt_r_raise),sum(ic.cnt_f_call),sum(ic.cnt_t_call),sum(ic.cnt_r_call),sum(ic.cnt_f_fold),sum(ic.cnt_t_fold),sum(ic.cnt_r_fold) FROM (SELECT cash_cache.id_player,cash_cache.id_limit,cash_cache.id_gametype,sum(cnt_hands) AS cnt_hands,sum(cnt_hands_won) AS cnt_hands_won,sum(amt_won) AS amt_won,cash_cache.limit_currency,sum(amt_won_curr_conv) AS amt_won_curr_conv,sum(amt_expected_won_curr_conv) AS amt_expected_won_curr_conv,sum(amt_bb_won) AS amt_bb_won,sum(amt_expected_bb_won) AS amt_expected_bb_won,sum(cnt_vpip) AS cnt_vpip,sum(cnt_walks) AS cnt_walks,sum(cnt_pfr) AS cnt_pfr,sum(cnt_pfr_opp) AS cnt_pfr_opp,sum(cnt_p_3bet) AS cnt_p_3bet,sum(cnt_p_3bet_opp) AS cnt_p_3bet_opp,sum(cnt_p_3bet_def_action_fold) AS cnt_p_3bet_def_action_fold,sum(cnt_p_3bet_def_opp) AS cnt_p_3bet_def_opp,sum(cnt_p_4bet) AS cnt_p_4bet,sum(cnt_p_4bet_opp) AS cnt_p_4bet_opp,sum(cnt_p_4bet_def_action_fold) AS cnt_p_4bet_def_action_fold,sum(cnt_p_4bet_def_opp) AS cnt_p_4bet_def_opp,sum(cnt_p_3bet_def_action_call) AS cnt_p_3bet_def_action_call,sum(cnt_p_4bet_after_raising) AS cnt_p_4bet_after_raising,sum(cnt_p_4bet_opp_when_open_raised) AS cnt_p_4bet_opp_when_open_raised,sum(cnt_p_squeeze) AS cnt_p_squeeze,sum(cnt_p_squeeze_opp) AS cnt_p_squeeze_opp,sum(cnt_wtsd) AS cnt_wtsd,sum(cnt_f_saw) AS cnt_f_saw,sum(cnt_wtsd_won) AS cnt_wtsd_won,sum(cnt_f_saw_won) AS cnt_f_saw_won,sum(cnt_f_cbet) AS cnt_f_cbet,sum(cnt_f_cbet_opp) AS cnt_f_cbet_opp,sum(cnt_t_cbet) AS cnt_t_cbet,sum(cnt_t_cbet_opp) AS cnt_t_cbet_opp,sum(cnt_r_cbet) AS cnt_r_cbet,sum(cnt_r_cbet_opp) AS cnt_r_cbet_opp,sum(cnt_f_cbet_success) AS cnt_f_cbet_success,sum(cnt_t_cbet_success) AS cnt_t_cbet_success,sum(cnt_r_cbet_success) AS cnt_r_cbet_success,sum(cnt_f_cbet_def_action_call) AS cnt_f_cbet_def_action_call,sum(cnt_f_cbet_def_opp) AS cnt_f_cbet_def_opp,sum(cnt_t_cbet_def_action_call) AS cnt_t_cbet_def_action_call,sum(cnt_t_cbet_def_opp) AS cnt_t_cbet_def_opp,sum(cnt_f_cbet_def_action_fold) AS cnt_f_cbet_def_action_fold,sum(cnt_t_cbet_def_action_fold) AS cnt_t_cbet_def_action_fold,sum(cnt_p_rfi_btn) AS cnt_p_rfi_btn,sum(cnt_p_open_opp_btn) AS cnt_p_open_opp_btn,sum(cnt_p_rfi_ep) AS cnt_p_rfi_ep,sum(cnt_p_open_opp_ep) AS cnt_p_open_opp_ep,sum(amt_r_call_won) AS amt_r_call_won,sum(amt_r_call) AS amt_r_call,sum(cnt_steal_att) AS cnt_steal_att,sum(cnt_steal_opp) AS cnt_steal_opp,sum(cnt_steal_def_action_raise) AS cnt_steal_def_action_raise,sum(cnt_steal_def_3bet_opp) AS cnt_steal_def_3bet_opp,sum(cnt_steal_def_action_fold) AS cnt_steal_def_action_fold,sum(cnt_steal_def_opp) AS cnt_steal_def_opp,sum(cnt_f_bet) AS cnt_f_bet,sum(cnt_f_raise) AS cnt_f_raise,sum(cnt_t_bet) AS cnt_t_bet,sum(cnt_t_raise) AS cnt_t_raise,sum(cnt_r_bet) AS cnt_r_bet,sum(cnt_r_raise) AS cnt_r_raise,sum(cnt_f_call) AS cnt_f_call,sum(cnt_t_call) AS cnt_t_call,sum(cnt_r_call) AS cnt_r_call,sum(cnt_f_fold) AS cnt_f_fold,sum(cnt_t_fold) AS cnt_t_fold,sum(cnt_r_fold) AS cnt_r_fold  FROM cash_limit, cash_cache WHERE  cash_cache.id_player = (SELECT id_player FROM player WHERE player_name_search=E'audrey92140'  AND id_site='2200')  AND cash_limit.id_limit=cash_cache.id_limit  AND ((cash_cache.id_gametype = 1))  GROUP BY cash_cache.id_player,cash_cache.id_limit,cash_cache.id_gametype,cash_cache.limit_currency) ic,player WHERE player.id_player=ic.id_player  GROUP BY ic.id_limit,ic.id_gametype,ic.limit_currency
`,

    keys: [
        "id_limit",
        "id_gametype",
        "cnt_hands",
        "cnt_hands_won",
        "limit_currency",
        "amt_won",
        "amt_won_curr_conv",
        "amt_expected_won_curr_conv",
        "amt_bb_won",
        "amt_expected_bb_won",
        "cnt_vpip",
        "cnt_walks",
        "cnt_pfr",
        "cnt_pfr_opp",
        "cnt_p_3bet",
        "cnt_p_3bet_opp",
        "cnt_p_3bet_def_action_fold",
        "cnt_p_3bet_def_opp",
        "cnt_p_4bet",
        "cnt_p_4bet_opp",
        "cnt_p_4bet_def_action_fold",
        "cnt_p_4bet_def_opp",
        "cnt_p_3bet_def_action_call",
        "cnt_p_4bet_after_raising",
        "cnt_p_4bet_opp_when_open_raised",
        "cnt_p_squeeze",
        "cnt_p_squeeze_opp",
        "cnt_wtsd",
        "cnt_f_saw",
        "cnt_wtsd_won",
        "cnt_f_saw_won",
        "cnt_f_cbet",
        "cnt_f_cbet_opp",
        "cnt_t_cbet",
        "cnt_t_cbet_opp",
        "cnt_r_cbet",
        "cnt_r_cbet_opp",
        "cnt_f_cbet_success",
        "cnt_t_cbet_success",
        "cnt_r_cbet_success",
        "cnt_f_cbet_def_action_call",
        "cnt_f_cbet_def_opp",
        "cnt_t_cbet_def_action_call",
        "cnt_t_cbet_def_opp",
        "cnt_f_cbet_def_action_fold",
        "cnt_t_cbet_def_action_fold",
        "cnt_p_rfi_btn",
        "cnt_p_open_opp_btn",
        "cnt_p_rfi_ep",
        "cnt_p_open_opp_ep",
        "amt_r_call_won",
        "amt_r_call",
        "cnt_steal_att",
        "cnt_steal_opp",
        "cnt_steal_def_action_raise",
        "cnt_steal_def_3bet_opp",
        "cnt_steal_def_action_fold",
        "cnt_steal_def_opp",
        "cnt_f_bet",
        "cnt_f_raise",
        "cnt_t_bet",
        "cnt_t_raise",
        "cnt_r_bet",
        "cnt_r_raise",
        "cnt_f_call",
        "cnt_t_call",
        "cnt_r_call",
        "cnt_f_fold",
        "cnt_t_fold",
        "cnt_r_fold"
    ],
};
